name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Latest version

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Latest version
      with:
        node-version: '20'  # Set Node.js version to 20

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: echo "Building the project..."

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Latest version
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Specify the directory to publish



